### ISSUE TITLE
No E-Mail-Notification via GitHub

### ISSUE THREAD

**Issue by thomasmerz** [thomasmerz/upptime#28]

**Comment by thomasmerz** [comment]
This is only possible with assignee = me in .upptimerc.yaml 👍🏻

**Comment by thomasmerz** [comment]
And with `Include your own updates` in https://github.com/settings/notifications

**Comment by thomas-merz** [comment]
Or when **assigning issues to an account different from the one that opens the issues** 🤔 So that this other account will get notified when new issues are opened (and closed?)…!?
