### ISSUE TITLE
Example: Scheduled maintenance tomorrow

### ISSUE THREAD

**Issue by thomasmerz** [thomasmerz/upptime#65]
This is an example of how you can set up a scheduled maintenance event. To set this up, create a new issue in your @upptime repository and add the label maintenance to it. Then, you can add details in the comments. Make sure you also add an HTML comment at the beginning of the issue, which looks like this:

More here: https://upptime.js.org/docs/scheduled-maintenance

**Comment by thomasmerz** [comment]
Original See https://github.com/upptime/upptime/issues/267

**Comment by thomasmerz** [comment]
This
```
start: 2021-03-12T00:30:00.220Z
end: 2021-03-12T02:00:00.220Z
```
means:
```
start: 2021-03-12T01:30:00.220Z
end: 2021-03-12T03:00:00.220Z
```
⚠️

**Comment by modem7** [comment]
Just an FYI - an easy way to generate the start/end string in bash is:


date +"%Y-%m-%dT%H:%M:%S%z"

That will also append the appropriate timezone as well.

Have tested this successfully here: https://github.com/modem7/Status/issues/31

**Comment by modem7** [comment]
Hopefully this will help people a bit more than the above.

https://rextester.com/OOJK1310

I've created a (probably poorly written) script that has everything required w/ appropriate TZ to create a maintenance issue.

```
#!/bin/bash
# Script to easily create maintenance window issue for Upptime.
# Author: modem7 - https://github.com/modem7

##################################
###### Change these values #######
##################################
# Edit Timezone if required
export TZ=Europe/London

# Enter how long your maintenance window is for
mainthour="1" # 0 value allowed
maintmin="30" # 0 value allowed

# Enter services to be down (make sure to keep the quotes, and comma separate the values)
expecteddown="website, analytics"

##################################
# Start time variable. Don't change.
    starttime=$(date +"%Y-%m-%dT%H:%M:%S%z")

# Maintenance window variables. Don't change.
    maintwindow="${mainthour} hours ${maintmin} minutes"

    endtime=$(date -d "${maintwindow} hence" +"%Y-%m-%dT%H:%M:%S%z")
##################################

# Output required fields for maintenance issue.
echo "#################### Copy values below ####################"
echo "Maintenance for $expecteddown"
echo "Lasting from $starttime to $endtime"
echo
echo "<!--"
echo "start: $starttime"
echo "end: $endtime"
echo "expectedDown: $expecteddown"
echo "-->"
echo "#################### Copy values above ####################"
```

**Comment by thomasmerz** [comment]
Reminder for me: **Timezone**!!!
